import { Router } from 'express';
import authRouter from './modules/auth/auth.routes.js';
import customerAuthRouter from './modules/customer-auth/customer-auth.routes.js';
import staffRouter from './modules/staff/staff.routes.js';
import countryRouter from './modules/country/country.routes.js';
import cityRouter from './modules/city/city.routes.js';
import categoryRouter from './modules/category/category.routes.js';
import attractionRouter from './modules/attraction/attraction.routes.js';
import supplierRouter from './modules/supplier/supplier.routes.js';
import tourRouter from './modules/tour/tour.routes.js';
import uploadRouter from './modules/upload/upload.routes.js';
import customerRouter from './modules/customer/customer.routes.js';
import agentRouter from './modules/agent/agent.routes.js';
import couponRouter from './modules/coupon/coupon.routes.js';
import exchangeRateRouter from './modules/exchange-rate/exchange-rate.routes.js';
import bookingRouter from './modules/booking/booking.routes.js';
import paymentRouter from './modules/payment/payment.routes.js';
import wishlistRouter from './modules/wishlist/wishlist.routes.js';
import reviewRouter from './modules/review/review.routes.js';
import reviewAdminRouter from './modules/review/review-admin.routes.js';
import alertRouter from './modules/alert/alert.routes.js';
import emailTemplateRouter from './modules/email-template/email-template.routes.js';
import blogRouter from './modules/blog/blog.routes.js';
import faqRouter from './modules/faq/faq.routes.js';
import bannerRouter from './modules/banner/banner.routes.js';
import destinationCategoryRouter from './modules/destination-category/destination-category.routes.js';
import statsRouter from './modules/stats/stats.routes.js';
import tourcmsRouter from './modules/integrations/tourcms/tourcms.routes.js';
import ventrataRouter from './modules/integrations/ventrata/ventrata.routes.js';
import searchRouter from './modules/search/search.routes.js';
import reservationRouter from './modules/reservation/reservation.routes.js';

const router = Router();

router.get('/health', (_req, res) => {
    res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

router.use('/auth/customer', customerAuthRouter);
router.use('/auth', authRouter);
router.use('/staff', staffRouter);
router.use('/countries', countryRouter);
router.use('/cities', cityRouter);
router.use('/categories', categoryRouter);
router.use('/attractions', attractionRouter);
router.use('/suppliers', supplierRouter);
router.use('/tours', tourRouter);
router.use('/tours', reviewRouter);
router.use('/reviews', reviewAdminRouter);
router.use('/uploads', uploadRouter);
router.use('/customers', customerRouter);
router.use('/agents', agentRouter);
router.use('/coupons', couponRouter);
router.use('/exchange-rates', exchangeRateRouter);
router.use('/bookings', bookingRouter);
router.use('/cart', reservationRouter);
router.use('/payments', paymentRouter);
router.use('/wishlist', wishlistRouter);
router.use('/alerts', alertRouter);
router.use('/email-templates', emailTemplateRouter);
router.use('/blogs', blogRouter);
router.use('/faqs', faqRouter);
router.use('/banners', bannerRouter);
router.use('/destination-categories', destinationCategoryRouter);
router.use('/stats', statsRouter);
router.use('/search', searchRouter);
router.use('/integrations/tourcms', tourcmsRouter);
router.use('/integrations/ventrata', ventrataRouter);

export default router;
